fixed issue with adder function
 return 'The sum of the 2 numbers ' '+${a+b}';
                                     ^^^^^^^^^
SyntaxError: Unexpected string
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\anujr\Desktop\Programs\node-js-playlist-master\nod
e-js-playlist-master\public\assets\app.js:57:13)
    at Module._compile (module.js:570:32)